Traceback (most recent call last):
  File "C:\Users\sandr\anaconda3\envs\renv\lib\site-packages\jupyter_cache\executors\utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "C:\Users\sandr\anaconda3\envs\renv\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\sandr\anaconda3\envs\renv\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\sandr\anaconda3\envs\renv\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\sandr\anaconda3\envs\renv\lib\asyncio\base_events.py", line 587, in run_until_complete
    return future.result()
  File "C:\Users\sandr\anaconda3\envs\renv\lib\site-packages\nbclient\client.py", line 664, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "C:\Users\sandr\anaconda3\envs\renv\lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\sandr\anaconda3\envs\renv\lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Loading relevant packages
import numpy as np
import pandas as pd
import statsmodels.formula.api as smf
import statsmodels.api as sm
import warnings
warnings.filterwarnings('ignore')
import seaborn as sns
import matplotlib.pyplot as plt
import random 
import time

rest_time = 10 # For time.sleep()

# !pip install patsy
import patsy

## pip install sklearn
from sklearn.linear_model import LassoCV
from sklearn.model_selection import train_test_split

## !pip install scipy
from scipy.stats import norm, expon, binom
## pip install econml
from econml.grf import RegressionForest, CausalForest, CausalIVForest as instrumental_forest
# from econml.dml import CausalForestDML as causal_forest
from econml.policy import PolicyForest, PolicyTree 
## Users function
from main import *

random.seed(12)
np.random.seed(12)
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mModuleNotFoundError[0m                       Traceback (most recent call last)
[1;32m~\AppData\Local\Temp/ipykernel_15908/2945750771.py[0m in [0;36m<module>[1;34m[0m
[0;32m     27[0m [1;32mfrom[0m [0meconml[0m[1;33m.[0m[0mpolicy[0m [1;32mimport[0m [0mPolicyForest[0m[1;33m,[0m [0mPolicyTree[0m[1;33m[0m[1;33m[0m[0m
[0;32m     28[0m [1;31m## Users function[0m[1;33m[0m[1;33m[0m[1;33m[0m[0m
[1;32m---> 29[1;33m [1;32mfrom[0m [0mmain[0m [1;32mimport[0m [1;33m*[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m     30[0m [1;33m[0m[0m
[0;32m     31[0m [0mrandom[0m[1;33m.[0m[0mseed[0m[1;33m([0m[1;36m12[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m

[1;31mModuleNotFoundError[0m: No module named 'main'
ModuleNotFoundError: No module named 'main'

